### ISSUE TITLE
Feature request: hubic.com OAuth

### ISSUE THREAD

**Issue by ed-miller** [alekseynemiro/Nemiro.OAuth.LoginForms#8]
Hi Aleksey,

thank your for last update. Droptbox works fine now.
I have a feature request. hubic.com is a storage provider like OneDrive, but much cheaper. Can you please integrate OAuth of hubic.com to LoginForms ?

It is very similar to G-Drive OAuth. So I suppose it will be easy copy and paste for your.

OAuth docs
https://api.hubic.com/docs/#/server-side

OAuth sandbox
https://api.hubic.com/sandbox/

Thank you!

Regards,
Ed

**Comment by alekseynemiro** [comment]
No, it will not be easy for me. 

I'll have: read the documentation; write the code; write documentation; check the correct operation of all of all clients, for .NET 3.5, 4.0, 4.5 and 4.6; write the change log; to make a new package (for .NET 3.5, 4.0, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1 and 4.6.2) and release. And all of this I will have to do for two separate projects: **OAuth** and **LoginForms** :-) Most likely, I will also have to write an examples. And to add a new client at the demonstration site.

This will require a lot of time, which I have not at the moment.

You can make yourself a new client. It will be easier, because except the code you no longer need to do.

When I get time, I'll try to make an example of a custom client for hubic.com. But I cannot say when it will be possible.

**Comment by ed-miller** [comment]
Thank you! No problem.
I done it myselft. As I said. I simply copy GoogleOAuth and rename and works fine. Overall it take me 45 Minutes!
